<<<<<<< HEAD
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
<<<<<<< HEAD
import environ
import os
from pathlib import Path


env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Now use the variables from .env
#SECRET_KEY = env('SECRET_KEY')
SECRET_KEY = os.getenv("SECRET_KEY") 
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
=======

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment file automatically
load_dotenv(os.path.join(BASE_DIR, "env/.env.dev"))


SECRET_KEY = os.getenv("SECRET_KEY")

>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
#SECRET_KEY = "django-insecure-jwq@&w8lv*hzxm*l9*+pk2f4@aa@t6eqf$c=9ueg5ix8%^su1t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
=======
# SECRET_KEY = "django-insecure-p$4ui1nc0fcfxfffp=tc@sufi8i=t7c)^_fd@xad&za2f7v3=!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)


# Application definition

=======
import os
import sys
import environ
from pathlib import Path

# 1. Initialize environ
env = environ.Env(
    DEBUG=(bool, False)
)

# 2 . Define BASE_DIR FIRST (3 levels up from config/settings/base.py)
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# 3 levels up from config/settings/base.py
# Add the 'apps' directory to the system path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# 3. Load the correct .env file
# This logic checks if ENV_NAME is set, else defaults to .env.dev
ENV_NAME = os.environ.get("ENV_NAME", "dev")
env_path = os.path.join(BASE_DIR, f".env.{ENV_NAME}")

if os.path.exists(env_path):
    environ.Env.read_env(env_path)
else:
    # Fallback to standard .env
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# --- IMPROVED SETTINGS (Pulling from .env) ---

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Application definition
>>>>>>> 29c3e84 (Initial clean production-ready commit)
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
<<<<<<< HEAD
<<<<<<< HEAD
=======
    "apps.core",
    "apps.users",
    "apps.dashboard",
    "apps.bmc",
    "apps.pbr",
    "apps.flora",
    "apps.fauna",
    'apps.testing',
>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)
=======
    
    # Third Party
    "crispy_forms",
    "crispy_bootstrap5",
    "django_htmx",
    
    # Internal Apps (Add yours here)
    "apps.core",
>>>>>>> 29c3e84 (Initial clean production-ready commit)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
<<<<<<< HEAD
=======
    "whitenoise.middleware.WhiteNoiseMiddleware", # Added for your static files
>>>>>>> 29c3e84 (Initial clean production-ready commit)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
<<<<<<< HEAD
=======
    "django_htmx.middleware.HtmxMiddleware", # Added for your cascading selects
>>>>>>> 29c3e84 (Initial clean production-ready commit)
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

<<<<<<< HEAD
<<<<<<< HEAD
ROOT_URLCONF = "config.urls.urls"
=======
#ROOT_URLCONF = "config.urls"
ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"
>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)
=======
ROOT_URLCONF = "config.urls"
>>>>>>> 29c3e84 (Initial clean production-ready commit)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
<<<<<<< HEAD
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
=======
        "DIRS": [os.path.join(BASE_DIR, 'templates')], # Added directory
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
>>>>>>> 29c3e84 (Initial clean production-ready commit)
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

<<<<<<< HEAD

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

<<<<<<< HEAD
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
=======
# The URL to use when referring to static files
STATIC_URL = 'static/'

# The directory where collectstatic will collect static files for deployment
# BASE_DIR / 'staticfiles' is a standard convention
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The directories where Django looks for additional static files (like your custom CSS)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
>>>>>>> 8356694 (Setup Dockerized Django project and fixed template errors)
=======
# Database Configuration using DATABASE_URL from .env
DATABASES = {
    "default": env.db(),
}

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata" # Set for your work in Odisha
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
>>>>>>> 29c3e84 (Initial clean production-ready commit)
